# Generated by Django 3.1.7 on 2021-04-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_id',
            new_name='invoice_customer_id',
        ),
    ]
