# Generated by Django 3.1.7 on 2021-03-31 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoice_detail_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
