# Generated by Django 3.1.7 on 2021-03-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210331_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_total',
            field=models.FloatField(),
        ),
    ]
