# Generated by Django 3.1.7 on 2021-09-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_product_product_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
