# Generated by Django 3.1.7 on 2021-04-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20210411_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_detail',
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice'),
        ),
    ]
