# Generated by Django 3.1.7 on 2021-04-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210411_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(default=0),
        ),
    ]
