# Generated by Django 4.1 on 2022-12-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20221214_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
